#index:
#    path: /
#    controller: App\Controller\DefaultController::index

load_client:
    path: /angular/{path}
    controller: \App\Controller\LoadClientController::load
    requirements:
        path: .*
    defaults:
        path: ""
