controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

load_client:
    path: /angular/{path}
    controller: \App\Controller\LoadClientController::load
    requirements:
        path: .*
    defaults:
        path: ""
